/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description List sources, filterable and paginated. Frontmatter only.
         */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Source
         * @description Read one source: frontmatter, paragraphs with anchors, apparatus.
         */
        get: operations["read_source_api_sources__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{record_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raw Source
         * @description The un-normalized file this record was normalized from. "Open
         *     original" (#25).
         */
        get: operations["raw_source_api_sources__record_id__raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Full-text search, wrapping ``memoria.index.search`` (#12).
         *
         *     The route applies no filter of its own: ``SearchFilters`` is built here
         *     only to carry the query params across the boundary, and every hit is
         *     ``memoria.index.search``'s own result, unmodified - no hydration, no SQL,
         *     written in this package (#64's acceptance criteria).
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Paragraph
         * @description One paragraph, carrying the stable anchor ``read(ref)`` accepts.
         *
         *     ``anchor`` comes from ``NormalizedRecord.anchor_id()`` - never
         *     re-derived as a string (#64's "where the fields come from").
         */
        Paragraph: {
            /** Anchor */
            anchor: string;
            /** Text */
            text: string;
        };
        /**
         * RawSourceResponse
         * @description The un-normalized file at ``original_file``, served as text.
         *
         *     ``original_locator`` is printed and never parsed - a pointer a person
         *     follows, not an offset (docs/normalized-record-schema.md).
         */
        RawSourceResponse: {
            /** Text */
            text: string;
            /** Original Locator */
            original_locator: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchResultOut"][];
        };
        /**
         * SearchResultOut
         * @description One search hit: the ``SRC-`` ID and paragraph anchor, and nothing
         *     else. ``memoria.index.SearchResult`` carries no text; this tool serves
         *     none either, for the same reason ``search_text`` (#12) does not - see
         *     ``docs/tool-surface.md``'s note on the amendment resolving #64 against
         *     #12's actual, current return shape.
         */
        SearchResultOut: {
            /** Src Id */
            src_id: string;
            /** Anchor */
            anchor: string;
            /** Source Type */
            source_type: string;
        };
        /**
         * SourceDetail
         * @description A source read in full: frontmatter, verbatim paragraphs, apparatus.
         *
         *     ``apparatus`` is the linked editorial apparatus - footnotes, bracketed
         *     asides, interpolations, editors' introductions - as a **separate
         *     collection**, never interleaved into ``paragraphs`` (§6). It is always
         *     empty today: nothing produces editorial records or links them to the
         *     record they annotate yet (``memoria.index``'s note on ``source_type``),
         *     so this field exists to be filled once that linkage does, not to be
         *     faked in the meantime.
         */
        SourceDetail: {
            /** Id */
            id: string;
            /** Source Type */
            source_type: string;
            /** Recorded Date */
            recorded_date: string;
            /** Event Date */
            event_date: string;
            /** Date Confidence */
            date_confidence: string;
            /** Contemporaneous */
            contemporaneous: boolean;
            /** Original File */
            original_file: string;
            /** Original Locator */
            original_locator: string;
            /** Paragraphs */
            paragraphs: components["schemas"]["Paragraph"][];
            /**
             * Apparatus
             * @default []
             */
            apparatus: components["schemas"]["SourceSummary"][];
        };
        /**
         * SourceListResponse
         * @description A page of ``list sources`` - paginated, per the acceptance criterion.
         */
        SourceListResponse: {
            /** Items */
            items: components["schemas"]["SourceSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * SourceSummary
         * @description One record's frontmatter, and nothing else - the list view's row.
         *
         *     "List sources... Returns frontmatter only, never bodies" (#64): the
         *     paragraphs a record carries are not on this model, only on
         *     ``SourceDetail``.
         */
        SourceSummary: {
            /** Id */
            id: string;
            /** Source Type */
            source_type: string;
            /** Recorded Date */
            recorded_date: string;
            /** Event Date */
            event_date: string;
            /** Date Confidence */
            date_confidence: string;
            /** Contemporaneous */
            contemporaneous: boolean;
            /** Original File */
            original_file: string;
            /** Original Locator */
            original_locator: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sources_api_sources_get: {
        parameters: {
            query?: {
                source_type?: string | null;
                date_confidence?: string | null;
                contemporaneous?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_source_api_sources__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raw_source_api_sources__record_id__raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                event_date?: string | null;
                recorded_date?: string | null;
                source_type?: string | null;
                contemporaneous?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
