/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description List sources, filterable and paginated. Frontmatter only.
         */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Source
         * @description Read one source: frontmatter, paragraphs with anchors, apparatus.
         */
        get: operations["read_source_api_sources__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{record_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raw Source
         * @description The un-normalized file this record was normalized from. "Open
         *     original" (#25).
         */
        get: operations["raw_source_api_sources__record_id__raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Locality
         * @description Whether this connection is local - the one fact "Reveal in editor"
         *     (#65) needs to decide whether to exist on this client at all. General
         *     on purpose: any future locality-gated action reads this same fact
         *     rather than each route re-deriving it (ADR-0002: no other surface may
         *     acquire a client-locality condition of its own).
         */
        get: operations["locality_api_locality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{record_id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal Source
         * @description "Reveal in editor" (#65): launch the un-normalized file this record
         *     was normalized from in the host's editor or file manager.
         *
         *     Refused for a non-local request even if the UI never should have shown
         *     the button that reached this - the server never trusts the client's
         *     own idea of whether it is local, only the same peer-address check
         *     ``/locality`` reports. This is what keeps the action purely additive
         *     (ADR-0002): a hosted client gets a plain 403, never a launch on a
         *     machine it is not sitting at.
         *
         *     ``opened: true`` is only ever returned once the launch has actually
         *     survived its grace period (``records._launch``) - a missing opener
         *     binary or one that exits immediately both raise ``LaunchError`` here,
         *     reported as a real error response rather than a 500 traceback or a
         *     claim this route cannot back up.
         */
        post: operations["reveal_source_api_sources__record_id__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read
         * @description Resolve one reference - the slide-over citation panel's read (§19.9).
         *
         *     Wraps ``memoria.records.read``, the same composed core the MCP tool
         *     surface's ``read(ref)`` calls, but narrower: a ``SRC-`` paragraph anchor
         *     (a search hit's or a paragraph's own ``anchor``) serves the cited text,
         *     its record and its curated-overlay backlinks (#20); a ``SUB-x/y`` entry
         *     reference - an overlay's own ``entry_links``/``exclusions`` - serves the
         *     entry's raw text, so a backlink is clickable into the same panel in both
         *     directions (#25's acceptance criteria) without a second read shape.
         *     Anything else - including a bare ``SUB-`` subject or a repository path
         *     that would otherwise resolve - is a 404: this route is not the MCP
         *     ``read(ref)`` tool and does not owe it the same contract (#145,
         *     ``_is_citable``). Ledgering the served read is the caller's job
         *     (``memoria.records.read``'s own docstring) - this route never imports
         *     ``memoria.ledger``, so an author's own read here writes nothing to
         *     ``events.jsonl``.
         */
        get: operations["read_api_read_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Subjects
         * @description The `SUBJECTS` tree's top level: the subjects on disk, each with its
         *     entry count computed from the entries actually there (#24) - an
         *     un-seeded repository (`memoria seed-subjects` never run) is an empty
         *     list, not an error, the same honesty ``list_sources`` keeps for an
         *     un-normalized one.
         */
        get: operations["list_subjects_api_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{subject_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entries
         * @description One subject's entries, for the `SUBJECTS` tree's second level.
         */
        get: operations["list_entries_api_subjects__subject_id__entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{subject_id}/entries/{entry_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Entry
         * @description Read one entry: #64's third subject read, built here for #148.
         *
         *     `GET /api/read?ref=SUB-x/y` (#25) already serves this same entry, but as
         *     the raw file verbatim, frontmatter included - the MCP tool surface's "the
         *     entry, verbatim" contract (`docs/tool-surface.md`), reached through a
         *     reference for the slide-over citation panel's backlink navigation. That
         *     is a different read from this one: the `SUBJECTS` tree needs an entry
         *     shaped like its `list subjects`/`list a subject's entries` siblings -
         *     parsed fields, not a raw blob - the same way `read_source` parses a
         *     record into paragraphs rather than pointing callers at `raw_source`.
         *     `load_entry` survives a renamed entry file the same way `find_entry_path`
         *     does (issue #16); a missing subject or entry is `SubjectError`, mapped to
         *     404 rather than the honest-empty-state `list_entries` gives a *known*
         *     subject with no entries.
         */
        get: operations["read_entry_api_subjects__subject_id__entries__entry_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Full-text search, wrapping ``memoria.index.search`` (#12).
         *
         *     The route applies no filter of its own: ``SearchFilters`` is built here
         *     only to carry the query params across the boundary, and every hit is
         *     ``memoria.index.search``'s own result, unmodified - no hydration, no SQL,
         *     written in this package (#64's acceptance criteria).
         *
         *     ``snippet=True`` is the one thing this route asks for that the MCP tool
         *     does not: the search dialog draws a fragment per hit (part 19 §19.8) and
         *     the core computes it, so the adapter still opens no database and reads no
         *     evidence. It is a locator, not evidence - #95.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CitationOut
         * @description One resolved reference - the slide-over citation panel's read (§19.9).
         *
         *     The single generic read the panel uses in both directions: a ``SRC-``
         *     paragraph anchor serves the cited text, its record and its backlinks
         *     (``overlay``); a ``SUB-x/y`` entry reference serves the entry's own text,
         *     with ``record``/``paragraph``/``overlay`` all ``None`` - a backlink is
         *     clickable into the same panel, and the panel does not need a second shape
         *     to render it (#25's "traverse in both directions"). Wraps
         *     ``memoria.records.read``, the same composed core the MCP tool surface
         *     calls, but narrower: only those two reference kinds resolve, and a bare
         *     ``SUB-`` subject or a repository path is a 404 (#145) - so this is the
         *     one generic reference read the viewer has, never a second one duplicating
         *     ``/sources/{id}`` or a browse over the repository.
         *
         *     ``anchor`` is the cited paragraph's own stable anchor, from
         *     ``NormalizedRecord.anchor_id()`` - served, not reconstructed client-side,
         *     the same "no reconstruction by the caller" discipline
         *     ``docs/tool-surface.md`` already holds for a search hit's anchor.
         *     ``None`` whenever ``paragraph`` is, the same pairing.
         */
        CitationOut: {
            /** Ref */
            ref: string;
            /** Citation */
            citation: string;
            /** Text */
            text: string;
            record?: components["schemas"]["SourceSummary"] | null;
            /** Paragraph */
            paragraph?: number | null;
            /** Anchor */
            anchor?: string | null;
            overlay?: components["schemas"]["ReadOverlayOut"] | null;
        };
        /**
         * EditorialRecordOut
         * @description One piece of editorial apparatus, linked to the paragraph it
         *     annotates (#25's "what the data actually is").
         *
         *     ``editorial_type`` is one of ``footnote``, ``bracketed-span``,
         *     ``interpolation`` or ``introduction``; a consumer renders whatever value
         *     is actually present rather than assuming that list is closed, the same
         *     posture ``SourceSummary.source_type`` already takes. ``retrospective``
         *     marks apparatus added after the fact, distinct from the evidence it
         *     annotates. ``linked_record_id``/``linked_anchor`` name the paragraph it
         *     attaches to - never inline in that paragraph's own text (§6).
         */
        EditorialRecordOut: {
            /** Editorial Type */
            editorial_type: string;
            /** Retrospective */
            retrospective: boolean;
            /** Linked Record Id */
            linked_record_id: string;
            /** Linked Anchor */
            linked_anchor: string;
            /** Text */
            text: string;
        };
        /**
         * EntryDetail
         * @description One entry read in full - #64's third subject read (#148): frontmatter
         *     plus its body, parsed into ``statements`` the same way ``SourceDetail``
         *     parses a record into ``paragraphs`` rather than serving one raw blob.
         *
         *     Distinct from ``GET /api/read?ref=SUB-x/y`` (#25's ``CitationOut``),
         *     which serves the entry's raw file verbatim, frontmatter included - the
         *     MCP tool surface's "the entry, verbatim" contract
         *     (``docs/tool-surface.md``), reached through a reference for the
         *     slide-over citation panel's backlink navigation. This is the `SUBJECTS`
         *     tree's own read, shaped like its ``SubjectSummary``/``EntrySummary``
         *     siblings rather than conflated with that one.
         */
        EntryDetail: {
            /** Id */
            id: string;
            /** Match Terms */
            match_terms: string[];
            /** Statements */
            statements: components["schemas"]["StatementOut"][];
        };
        /** EntryListResponse */
        EntryListResponse: {
            /** Items */
            items: components["schemas"]["EntrySummary"][];
        };
        /**
         * EntrySummary
         * @description One entry under a subject - CONTEXT.md's vocabulary, not "item" or
         *     "record" (#24's acceptance criteria).
         */
        EntrySummary: {
            /** Id */
            id: string;
            /** Match Terms */
            match_terms: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LocalityOut
         * @description Whether this connection's client is on the same machine as the
         *     server.
         *
         *     "Reveal in editor" (#65)'s one locality fact - general on purpose, per
         *     ``docs/adr/0002-ui-is-a-react-client.md``'s "no other surface may
         *     acquire a client-locality condition" of its own: any future
         *     locality-gated action reads this same field rather than deriving one.
         */
        LocalityOut: {
            /** Is Local */
            is_local: boolean;
        };
        /**
         * Paragraph
         * @description One paragraph, carrying the stable anchor ``read(ref)`` accepts.
         *
         *     ``anchor`` comes from ``NormalizedRecord.anchor_id()`` - never
         *     re-derived as a string (#64's "where the fields come from").
         */
        Paragraph: {
            /** Anchor */
            anchor: string;
            /** Text */
            text: string;
        };
        /**
         * RawSourceResponse
         * @description The un-normalized file at ``original_file``, served as text.
         *
         *     ``original_locator`` is printed and never parsed - a pointer a person
         *     follows, not an offset (docs/normalized-record-schema.md).
         */
        RawSourceResponse: {
            /** Text */
            text: string;
            /** Original Locator */
            original_locator: string;
        };
        /**
         * ReadOverlayOut
         * @description The curated overlay a decorated paragraph read carries (#20):
         *     mirrors ``memoria.index.ReadOverlay`` field for field. ``citing_settlements``
         *     is always empty in this build - settlements have no durable storage yet
         *     (#20's own docstring) - and stays on the shape rather than being dropped,
         *     the same forward-compatibility call ``ReadOverlay`` itself makes.
         */
        ReadOverlayOut: {
            /** Entry Links */
            entry_links: string[];
            /** Exclusions */
            exclusions: string[];
            /** Citing Settlements */
            citing_settlements: string[];
        };
        /**
         * RevealSourceResponse
         * @description Confirms "Reveal in editor" (#65) launched.
         *
         *     Carries no other state - the editor or file manager runs on the host,
         *     outside this response.
         */
        RevealSourceResponse: {
            /** Opened */
            opened: boolean;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchResultOut"][];
        };
        /**
         * SearchResultOut
         * @description One search hit: the ``SRC-`` ID, the paragraph anchor, and a snippet.
         *
         *     ``memoria.index.SearchResult`` carries no paragraph text and this route
         *     serves none either, for the same reason ``search_text`` (#12) does not -
         *     see ``docs/tool-surface.md``'s "search_text(query, filters)" section,
         *     "What it returns", which is where that constraint is recorded.
         *
         *     ``snippet`` is not that text. It is the match locator #95 settled on: a
         *     truncated fragment of the index's copy, matched terms wrapped in
         *     ``index.SNIPPET_MATCH_START``/``_END``, for drawing a hit row (part 19
         *     §19.8). A client splits on those marks; it never renders the snippet as
         *     markup, and it never feeds it to ``read``. Evidence arrives when the
         *     reader clicks the hit and the slide-over reads ``anchor`` (§19.9).
         *
         *     Every field of ``index.SearchResult`` has a counterpart here, and
         *     ``test_web_app.py`` fails if one stops having one - the generated-types
         *     check cannot see a field the core has and this model dropped, because
         *     the schema stays self-consistent, just impoverished.
         */
        SearchResultOut: {
            /** Src Id */
            src_id: string;
            /** Anchor */
            anchor: string;
            /** Source Type */
            source_type: string;
            /** Snippet */
            snippet?: string | null;
        };
        /**
         * SourceDetail
         * @description A source read in full: frontmatter, verbatim paragraphs, apparatus.
         *
         *     ``apparatus`` is the linked editorial apparatus - footnotes, bracketed
         *     asides, interpolations, editors' introductions - as a **separate
         *     collection**, never interleaved into ``paragraphs`` (§6). It is always
         *     empty today: nothing produces editorial records or links them to the
         *     record they annotate yet (``memoria.index``'s note on ``source_type``),
         *     so this field exists to be filled once that linkage does, not to be
         *     faked in the meantime.
         */
        SourceDetail: {
            /** Id */
            id: string;
            /** Source Type */
            source_type: string;
            /** Recorded Date */
            recorded_date: string;
            /** Event Date */
            event_date: string;
            /** Date Confidence */
            date_confidence: string;
            /** Contemporaneous */
            contemporaneous: boolean;
            /** Original File */
            original_file: string;
            /** Original Locator */
            original_locator: string;
            /** Paragraphs */
            paragraphs: components["schemas"]["Paragraph"][];
            /**
             * Apparatus
             * @default []
             */
            apparatus: components["schemas"]["EditorialRecordOut"][];
        };
        /**
         * SourceListResponse
         * @description A page of ``list sources`` - paginated, per the acceptance criterion.
         */
        SourceListResponse: {
            /** Items */
            items: components["schemas"]["SourceSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * SourceSummary
         * @description One record's frontmatter, and nothing else - the list view's row.
         *
         *     "List sources... Returns frontmatter only, never bodies" (#64): the
         *     paragraphs a record carries are not on this model, only on
         *     ``SourceDetail``.
         */
        SourceSummary: {
            /** Id */
            id: string;
            /** Source Type */
            source_type: string;
            /** Recorded Date */
            recorded_date: string;
            /** Event Date */
            event_date: string;
            /** Date Confidence */
            date_confidence: string;
            /** Contemporaneous */
            contemporaneous: boolean;
            /** Original File */
            original_file: string;
            /** Original Locator */
            original_locator: string;
        };
        /**
         * StatementOut
         * @description One paragraph of an entry's body, with its badge if it has one.
         *
         *     Mirrors ``memoria.subjects.Statement`` field for field. ``badge`` is
         *     ``None`` for author testimony - the absence of a badge *is* the
         *     attribution (part 06 §9.5) - never re-derived by a consumer as "no
         *     badge shown".
         */
        StatementOut: {
            /** Badge */
            badge: string | null;
            /** Text */
            text: string;
        };
        /** SubjectListResponse */
        SubjectListResponse: {
            /** Items */
            items: components["schemas"]["SubjectSummary"][];
        };
        /**
         * SubjectSummary
         * @description One subject - the `SUBJECTS` tree's top level (#24).
         *
         *     ``entry_count`` is computed from the entries actually on disk, never
         *     hardcoded (#24's acceptance criteria) - the same discipline
         *     ``SourceListResponse.total`` keeps for sources.
         */
        SubjectSummary: {
            /** Id */
            id: string;
            /** Entry Count */
            entry_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sources_api_sources_get: {
        parameters: {
            query?: {
                source_type?: string | null;
                date_confidence?: string | null;
                contemporaneous?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_source_api_sources__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raw_source_api_sources__record_id__raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locality_api_locality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalityOut"];
                };
            };
        };
    };
    reveal_source_api_sources__record_id__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_read_get: {
        parameters: {
            query: {
                ref: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_api_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectListResponse"];
                };
            };
        };
    };
    list_entries_api_subjects__subject_id__entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_entry_api_subjects__subject_id__entries__entry_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
                entry_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                event_date?: string | null;
                recorded_date?: string | null;
                source_type?: string | null;
                contemporaneous?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
