/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description List sources, filterable and paginated. Frontmatter only.
         */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Source
         * @description Read one source: frontmatter, paragraphs with anchors, apparatus.
         */
        get: operations["read_source_api_sources__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{record_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raw Source
         * @description The un-normalized file this record was normalized from. "Open
         *     original" (#25).
         */
        get: operations["raw_source_api_sources__record_id__raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Locality
         * @description Whether this connection is local - the one fact "Reveal in editor"
         *     (#65) needs to decide whether to exist on this client at all. General
         *     on purpose: any future locality-gated action reads this same fact
         *     rather than each route re-deriving it (ADR-0002: no other surface may
         *     acquire a client-locality condition of its own).
         */
        get: operations["locality_api_locality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{record_id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal Source
         * @description "Reveal in editor" (#65): launch the un-normalized file this record
         *     was normalized from in the host's editor or file manager.
         *
         *     Refused for a non-local request even if the UI never should have shown
         *     the button that reached this - the server never trusts the client's
         *     own idea of whether it is local, only the same peer-address check
         *     ``/locality`` reports. This is what keeps the action purely additive
         *     (ADR-0002): a hosted client gets a plain 403, never a launch on a
         *     machine it is not sitting at.
         *
         *     ``opened: true`` is only ever returned once the launch has actually
         *     survived its grace period (``records._launch``) - a missing opener
         *     binary or one that exits immediately both raise ``LaunchError`` here,
         *     reported as a real error response rather than a 500 traceback or a
         *     claim this route cannot back up.
         */
        post: operations["reveal_source_api_sources__record_id__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read
         * @description Resolve one reference - the slide-over citation panel's read (§19.9).
         *
         *     Wraps ``memoria.records.read``, the same composed core the MCP tool
         *     surface's ``read(ref)`` calls, but narrower: a ``SRC-`` paragraph anchor
         *     (a search hit's or a paragraph's own ``anchor``) serves the cited text,
         *     its record and its curated-overlay backlinks (#20); a ``SUB-x/y`` entry
         *     reference - an overlay's own ``entry_links``/``exclusions`` - serves the
         *     entry's raw text, so a backlink is clickable into the same panel in both
         *     directions (#25's acceptance criteria) without a second read shape.
         *     Anything else - including a bare ``SUB-`` subject or a repository path
         *     that would otherwise resolve - is a 404: this route is not the MCP
         *     ``read(ref)`` tool and does not owe it the same contract (#145,
         *     ``_is_citable``). Ledgering the served read is the caller's job
         *     (``memoria.records.read``'s own docstring) - this route never imports
         *     ``memoria.ledger``, so an author's own read here writes nothing to
         *     ``events.jsonl``.
         */
        get: operations["read_api_read_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Subjects
         * @description The `SUBJECTS` tree's top level: the subjects on disk, each with its
         *     entry count computed from the entries actually there (#24) - an
         *     un-seeded repository (`memoria seed-subjects` never run) is an empty
         *     list, not an error, the same honesty ``list_sources`` keeps for an
         *     un-normalized one - and since #157 an empty list that says which of the
         *     two it is, in ``is_built``.
         */
        get: operations["list_subjects_api_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{subject_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entries
         * @description One subject's entries, for the `SUBJECTS` tree's second level.
         */
        get: operations["list_entries_api_subjects__subject_id__entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{subject_id}/entries/{entry_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Entry
         * @description One entry read whole - #64's third subject read, built in #157.
         *
         *     `GET /api/read?ref=SUB-x/y` (#25) serves this same entry, but as the raw
         *     file verbatim, frontmatter included - the MCP tool surface's "the entry,
         *     verbatim" contract (`docs/tool-surface.md`), reached through a reference
         *     for the slide-over citation panel's backlink navigation. That is a
         *     different read from this one (#148): the `SUBJECTS` tree needs an entry
         *     shaped like its `list subjects`/`list a subject's entries` siblings -
         *     parsed fields, not a raw blob - the same way `read_source` parses a record
         *     into paragraphs rather than pointing callers at `raw_source`.
         *
         *     Served through ``serve_entry`` rather than ``load_entry`` (#26): the
         *     author edits match terms from this surface, and ADR-0003's staleness
         *     check compares against *the file as it was read*, so the token has to be
         *     minted by the read that produced what is on screen rather than by the
         *     write that follows it.
         *
         *     Resolves an entry whose file has been renamed: ``serve_entry`` goes
         *     through ``find_entry_path``, which falls back to matching the
         *     frontmatter ``id``, so #16's stable ``SUB-x/y`` IDs survive a rename on
         *     disk and this route inherits that without repeating it.
         *
         *     ``extra`` is not served - it exists so a rewrite does not drop an
         *     unmodelled frontmatter key, not to be published (``EntryDetail``).
         *
         *     The gathered set and appearances are not here either, and that is the
         *     §8.11 separation rather than an economy: this is a read of the entry
         *     *file*, and those two are index reads with their own build signal and
         *     their own failure. They have their own routes below.
         */
        get: operations["read_entry_api_subjects__subject_id__entries__entry_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{subject_id}/entries/{entry_slug}/gathered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Gathered Set
         * @description An entry's gathered set, with the author's overlay legible on it.
         *
         *     ``gather`` has already applied the overlay - it drops an excluded anchor
         *     and adds a pinned one - so membership needs nothing here. What it does
         *     not carry is the *act*: which anchors the author pinned, who did it and
         *     when. That is on the entry file (part 04 §42 keeps it there, so it
         *     survives the index being deleted), and joining the two is this route's
         *     whole job.
         *
         *     The exclusions are served separately because they are absent from
         *     ``items`` by construction. A surface that got only the list would show a
         *     shorter set with no account of why, which is an author act rendered as
         *     nothing.
         */
        get: operations["read_gathered_set_api_subjects__subject_id__entries__entry_slug__gathered_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{subject_id}/entries/{entry_slug}/appearances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Appearances
         * @description An entry's appearances - the already-written prose it touches.
         *
         *     ``engine_supported`` is what stops an empty list from meaning two
         *     things. For a Person it means the lexical pass found nothing; for a
         *     Theme or an Arc it means the pass never ran, and will not until the
         *     audit at M5 (part 06 §8.11). ``memoria.index.appearances_supported``
         *     decides, the same predicate ``compute_appearances`` skips on.
         *
         *     The entry is served first so an unknown entry is a 404 here too, rather
         *     than an empty list for something that does not exist.
         */
        get: operations["read_appearances_api_subjects__subject_id__entries__entry_slug__appearances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{subject_id}/entries/{entry_slug}/match-terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Match Terms
         * @description Replace an entry's match terms - the first durable write over HTTP.
         *
         *     Match terms are author-owned (part 06 §8.2), so this commits as the
         *     author: ``repository_actor`` supplies the identity from the repository's
         *     own git config, never from the request, because ADR-0002 forbids
         *     assuming the browser and the repository share a machine and a name in a
         *     payload is an unverified claim about who acted.
         *
         *     The three outcomes, each a different status:
         *
         *     - **409** for a stale token. The file changed since the client read it -
         *       in Obsidian, or in another tab - and nothing was written, merged or
         *       partially applied (ADR-0003 decision 1). The client re-reads for the
         *       current content and a fresh token; this response deliberately carries
         *       neither (decision 5), because #64 already builds that read.
         *     - **400** for a malformed match term, refused by ``set_match_terms``
         *       before the file is touched.
         *     - **500** for a write that cannot be attempted - no configured git
         *       identity, or a failing commit.
         *
         *     On success the *new* token is returned, because the write has just
         *     invalidated the one the client presented and the editor is still open
         *     over the file.
         */
        put: operations["update_match_terms_api_subjects__subject_id__entries__entry_slug__match_terms_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Full-text search, wrapping ``memoria.index.search`` (#12).
         *
         *     The route applies no filter of its own: ``SearchFilters`` is built here
         *     only to carry the query params across the boundary, and every hit is
         *     ``memoria.index.search``'s own result, unmodified - no hydration, no SQL,
         *     written in this package (#64's acceptance criteria).
         *
         *     ``snippet=True`` is the one thing this route asks for that the MCP tool
         *     does not: the search dialog draws a fragment per hit (part 19 §19.8) and
         *     the core computes it, so the adapter still opens no database and reads no
         *     evidence. It is a locator, not evidence - #95.
         *
         *     ``is_built`` reports whether the index exists at all (#157), so a client
         *     can tell "never indexed" from "nothing matched" - the same empty list
         *     otherwise.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manuscript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Manuscript
         * @description The `MANUSCRIPT` tree: chapters and sections in outline order, each
         *     labelled by its brief's first line. Honest about an empty repository
         *     through ``is_built`` (#157's convention), the way the other trees are.
         */
        get: operations["read_manuscript_api_manuscript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Section
         * @description The Section surface, composed at this call (part 19 §19.5 / §19.11):
         *     the brief, the draft with each paragraph's not-current judgements, the
         *     entries in scope, and the decisions and questions from the sessions
         *     that touched it. Nothing here is stored section state - see
         *     ``memoria.section``.
         */
        get: operations["read_section_api_sections__section_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sections/{section_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Review
         * @description The Review surface: the results of the audit the author ran on this
         *     section - a read over the verdicts a session recorded, and nothing
         *     else. Findings arrive as disagreement sets with the resolutions their
         *     shape admits; the resolution list is read off the set, never a stored
         *     label (part 06 §8.10).
         */
        get: operations["read_review_api_sections__section_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sections/{section_id}/paragraphs/{paragraph_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rewrite Paragraph
         * @description Apply a proposed rewrite to one paragraph of a section's draft - the
         *     author's explicit act from Review, and the surface's one write.
         *
         *     Through the single write path (ADR-0003), the same three outcomes
         *     ``update_match_terms`` has: **409** for a draft changed since Review
         *     read it (nothing written, nothing merged; the client re-reads for the
         *     current draft and a fresh token), **400** for a paragraph the draft
         *     does not have or an empty rewrite, **500** for a write that cannot be
         *     attempted. Commits as the author - ``repository_actor``, never a name
         *     in the payload (ADR-0002) - because the click is the authorization
         *     (part 10 §19.3) and the applied prose is now the author's, the same
         *     class of thing as an edit made in Obsidian. The only file this can
         *     reach is ``draft.md``; no route edits a brief.
         */
        put: operations["rewrite_paragraph_api_sections__section_id__paragraphs__paragraph_index__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppearanceOut
         * @description One manuscript passage an entry turns out to touch (part 06 §8.11).
         *
         *     ``note`` names the match term that found it. No pin or exclude field
         *     here, unlike ``GatheredSourceOut``, and that is the design rather than
         *     an omission: an author act against one passage would be a durable
         *     pointer into mutable prose, which part 04 §4.1 forbids.
         */
        AppearanceOut: {
            /** Src Id */
            src_id: string;
            /** Anchor */
            anchor: string;
            /** Note */
            note: string;
        };
        /**
         * AppearancesResponse
         * @description An entry's appearances, and whether an engine could produce any.
         *
         *     Kept in its own response rather than folded onto ``EntryDetail``
         *     alongside the gathered set, because part 06 §8.11's separation is the
         *     point: a gathered set is evidence to write *from*, appearances are prose
         *     already written, and merging them would put manuscript text into what a
         *     writing agent reads as material.
         *
         *     ``engine_supported`` is ``memoria.index.appearances_supported``. False
         *     for Themes and Arcs, whose engine waits for the audit at M5 - without
         *     it, an empty list says "nothing appears" when the truth is "nothing has
         *     looked yet".
         *
         *     ``is_built`` reports ``memoria rebuild``, as elsewhere.
         */
        AppearancesResponse: {
            /** Items */
            items: components["schemas"]["AppearanceOut"][];
            /** Is Built */
            is_built: boolean;
            /** Engine Supported */
            engine_supported: boolean;
        };
        /**
         * CitationOut
         * @description One resolved reference - the slide-over citation panel's read (§19.9).
         *
         *     The single generic read the panel uses in both directions: a ``SRC-``
         *     paragraph anchor serves the cited text, its record and its backlinks
         *     (``overlay``); a ``SUB-x/y`` entry reference serves the entry's own text,
         *     with ``record``/``paragraph``/``overlay`` all ``None`` - a backlink is
         *     clickable into the same panel, and the panel does not need a second shape
         *     to render it (#25's "traverse in both directions"). Wraps
         *     ``memoria.records.read``, the same composed core the MCP tool surface
         *     calls, but narrower: only those two reference kinds resolve, and a bare
         *     ``SUB-`` subject or a repository path is a 404 (#145) - so this is the
         *     one generic reference read the viewer has, never a second one duplicating
         *     ``/sources/{id}`` or a browse over the repository.
         *
         *     ``anchor`` is the cited paragraph's own stable anchor, from
         *     ``NormalizedRecord.anchor_id()`` - served, not reconstructed client-side,
         *     the same "no reconstruction by the caller" discipline
         *     ``docs/tool-surface.md`` already holds for a search hit's anchor.
         *     ``None`` whenever ``paragraph`` is, the same pairing.
         *
         *     ``EntryDetail`` is **not** a second copy of this for entries, and the two
         *     are not collapsible (#157). Reading ``SUB-x/y`` here serves the entry's
         *     raw text for the panel and nothing else - no ``match_terms``, no badges,
         *     no curated overlay. The entry read serves the entry's own shape. Both
         *     exist because they answer different questions, and #25's one generic
         *     reference read stays exactly as it is.
         */
        CitationOut: {
            /** Ref */
            ref: string;
            /** Citation */
            citation: string;
            /** Text */
            text: string;
            record?: components["schemas"]["SourceSummary"] | null;
            /** Paragraph */
            paragraph?: number | null;
            /** Anchor */
            anchor?: string | null;
            overlay?: components["schemas"]["ReadOverlayOut"] | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Citation */
            citation: string;
        };
        /**
         * DisagreementMemberOut
         * @description One member of a finding's disagreement set - ``kind`` is one of
         *     ``passage``, ``entry``, ``source``, ``decision``, ``brief``; ``ref`` is
         *     that kind's own reference form (``memoria.audit.DisagreementMember``).
         */
        DisagreementMemberOut: {
            /** Kind */
            kind: string;
            /** Ref */
            ref: string;
        };
        /**
         * EditorialRecordOut
         * @description One piece of editorial apparatus, linked to the paragraph it
         *     annotates (#25's "what the data actually is").
         *
         *     ``editorial_type`` is one of ``footnote``, ``bracketed-span``,
         *     ``interpolation`` or ``introduction``; a consumer renders whatever value
         *     is actually present rather than assuming that list is closed, the same
         *     posture ``SourceSummary.source_type`` already takes. ``retrospective``
         *     marks apparatus added after the fact, distinct from the evidence it
         *     annotates. ``linked_record_id``/``linked_anchor`` name the paragraph it
         *     attaches to - never inline in that paragraph's own text (§6).
         */
        EditorialRecordOut: {
            /** Editorial Type */
            editorial_type: string;
            /** Retrospective */
            retrospective: boolean;
            /** Linked Record Id */
            linked_record_id: string;
            /** Linked Anchor */
            linked_anchor: string;
            /** Text */
            text: string;
        };
        /**
         * EntryDetail
         * @description One entry read whole - #64's third subject read, built here (#148,
         *     #157).
         *
         *     Distinct from ``GET /api/read?ref=SUB-x/y`` (#25's ``CitationOut``),
         *     which serves the entry's raw file verbatim, frontmatter included - the
         *     MCP tool surface's "the entry, verbatim" contract
         *     (``docs/tool-surface.md``), reached through a reference for the
         *     slide-over citation panel's backlink navigation. This is the `SUBJECTS`
         *     tree's own read, shaped like its ``SubjectSummary``/``EntrySummary``
         *     siblings rather than conflated with that one.
         *
         *     ``statements`` is the body split by ``memoria.subjects.parse_statements``:
         *     Memoria's badged statements and the author's unbadged testimony are
         *     shared territory in the same body (part 06 §8.2), and splitting them is
         *     what keeps them distinguishable rather than merely visually different.
         *
         *     Neither ``extra`` nor the raw ``body`` is here. ``extra`` exists so a
         *     rewrite does not drop an unmodelled frontmatter key (``Entry.extra``),
         *     not to be published; the parsed statements are the served form of the
         *     body, and a client that wants the markdown is asking for the file rather
         *     than for the entry.
         *
         *     ``token`` is ``memoria.write.serve``'s content hash of the entry file as
         *     it was served (ADR-0003 decision 1), opaque to the client and presented
         *     back on a match-term write. This is where the staleness token first
         *     crosses HTTP: entry files are editable in Obsidian too, so a write has
         *     to be checked against the file the client actually read rather than
         *     against whatever is on disk when it arrives.
         */
        EntryDetail: {
            /** Id */
            id: string;
            /** Match Terms */
            match_terms: string[];
            /** Statements */
            statements: components["schemas"]["StatementOut"][];
            /**
             * Overlay
             * @default []
             */
            overlay: components["schemas"]["OverlayActOut"][];
            /** Token */
            token: string;
        };
        /**
         * EntryListResponse
         * @description One subject's entries, for the `SUBJECTS` tree's second level.
         *
         *     Carries no ``is_built``, and the omission is a decision rather than an
         *     oversight (#157): a subject that exists with no entries is genuinely
         *     empty. There is no third state to report, so there is no flag.
         */
        EntryListResponse: {
            /** Items */
            items: components["schemas"]["EntrySummary"][];
        };
        /**
         * EntrySummary
         * @description One entry under a subject - CONTEXT.md's vocabulary, not "item" or
         *     "record" (#24's acceptance criteria).
         */
        EntrySummary: {
            /** Id */
            id: string;
            /** Match Terms */
            match_terms: string[];
        };
        /**
         * FindingOut
         * @description One finding, as the audit recorded it (part 06 §8.10): a disagreement
         *     set, prose stating how they disagree, a confidence, the subject that
         *     raised it, and an optional proposed rewrite. ``resolutions`` is read off
         *     the set's shape by ``Finding.available_resolutions`` - never stored,
         *     never a category. ``paragraph_index``/``paragraph_text`` locate it for
         *     this read only.
         */
        FindingOut: {
            /** Paragraph Index */
            paragraph_index: number;
            /** Paragraph Text */
            paragraph_text: string;
            /** Entry Id */
            entry_id: string;
            /** Subject Id */
            subject_id: string;
            /** Confidence */
            confidence: string;
            /** Statement */
            statement: string;
            /** Disagreement Set */
            disagreement_set: components["schemas"]["DisagreementMemberOut"][];
            /** Resolutions */
            resolutions: string[];
            /** Patch */
            patch?: string | null;
        };
        /**
         * GatheredSetResponse
         * @description An entry's gathered set, and the exclusions kept out of it.
         *
         *     ``items`` is ``memoria.index.gather``'s result, which has already
         *     applied the overlay: a pinned anchor is in it whatever the pass found,
         *     and an excluded one is gone. ``excluded`` carries those removed acts
         *     separately, because an exclusion the surface cannot render is an author
         *     act with nothing to show for it - the reader sees a shorter list and no
         *     reason for it.
         *
         *     ``is_built`` is ``memoria.index.is_built``, the same field and the same
         *     meaning as on ``SearchResponse``: an empty gathered set with it false
         *     means the corpus was never indexed, which is a different fact from an
         *     entry nothing matched. An entry with an empty gathered set is a valid
         *     state either way (part 06 §8.2), never an error.
         */
        GatheredSetResponse: {
            /** Items */
            items: components["schemas"]["GatheredSourceOut"][];
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["OverlayActOut"][];
            /** Is Built */
            is_built: boolean;
        };
        /**
         * GatheredSourceOut
         * @description One paragraph in an entry's gathered set (part 06 §8.3), with the
         *     author's overlay act over it if there is one.
         *
         *     ``anchor`` is the whole address a reader needs - it is what
         *     ``/api/read`` resolves - because the gathered set has no stable ID of
         *     its own: it is derived, asserts nothing, and nothing outside it ever
         *     names one (``memoria.index.GatheredSource``).
         *
         *     ``pinned`` is ``gather``'s own flag - membership. ``overlay_action`` and
         *     the two fields after it are the *act* behind it, read off the entry
         *     file: ``"pin"``, ``"exclude"``, or ``None`` where the pass alone
         *     accounts for the row. Both are served because they answer different
         *     questions and an excluded anchor is not in ``items`` at all - see
         *     ``GatheredSetResponse``.
         */
        GatheredSourceOut: {
            /** Src Id */
            src_id: string;
            /** Anchor */
            anchor: string;
            /** Pinned */
            pinned: boolean;
            /** Overlay Action */
            overlay_action?: string | null;
            /** Actor Name */
            actor_name?: string | null;
            /** At */
            at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LocalityOut
         * @description Whether this connection's client is on the same machine as the
         *     server.
         *
         *     "Reveal in editor" (#65)'s one locality fact - general on purpose, per
         *     ``docs/adr/0002-ui-is-a-react-client.md``'s "no other surface may
         *     acquire a client-locality condition" of its own: any future
         *     locality-gated action reads this same field rather than deriving one.
         */
        LocalityOut: {
            /** Is Local */
            is_local: boolean;
        };
        /**
         * ManuscriptOutline
         * @description The `MANUSCRIPT` tree: the ordered tree of chapters and sections,
         *     which *is* the outline - there is no outline file (part 04 §2.1).
         *     ``is_built`` is whether ``chapters/`` exists at all, the same
         *     "which empty is this" flag the other three trees carry (#157).
         */
        ManuscriptOutline: {
            /** Chapters */
            chapters: components["schemas"]["OutlineChapterOut"][];
            /** Is Built */
            is_built: boolean;
        };
        /**
         * MatchTermsResponse
         * @description What an accepted match-term write stored, and a fresh token.
         *
         *     The new token is served so the editor stays usable without a reload:
         *     the file it holds a token for has just changed - by its own write - so
         *     the one it presented is now stale by construction.
         */
        MatchTermsResponse: {
            /** Match Terms */
            match_terms: string[];
            /** Token */
            token: string;
        };
        /**
         * MatchTermsUpdate
         * @description A match-term write: the terms to store, and the token the entry was
         *     served with (ADR-0003).
         *
         *     The token is the whole staleness check from the client's side - it
         *     presents back what ``EntryDetail`` gave it, unread and unmodified, and a
         *     file changed underneath since then is rejected rather than merged.
         */
        MatchTermsUpdate: {
            /** Token */
            token: string;
            /** Match Terms */
            match_terms: string[];
        };
        /**
         * NotCurrentOut
         * @description One not-current judgement against a paragraph: the entry it was
         *     checked against, the judgement kind (``engagement`` or
         *     ``audit_verdict``), and the cause - one of ``memoria.audit``'s
         *     ``STALENESS_CAUSES``, rendered as it is rather than mapped.
         */
        NotCurrentOut: {
            /** Entry Id */
            entry_id: string;
            /** Kind */
            kind: string;
            /** Cause */
            cause: string;
        };
        /** OutlineChapterOut */
        OutlineChapterOut: {
            /** Id */
            id: string;
            /** Number */
            number: number;
            /** Excerpt */
            excerpt: string;
            /** Sections */
            sections: components["schemas"]["OutlineSectionOut"][];
        };
        /**
         * OutlineSectionOut
         * @description One section row of the `MANUSCRIPT` tree. ``excerpt`` is the first
         *     line of the brief, shortened - a brief has no title field (part 04
         *     §2.1), so the tree shows its prose rather than inventing a name.
         *     ``has_draft`` tells a planned section (brief written, draft empty -
         *     CONTEXT.md's "Outline") from one with prose.
         */
        OutlineSectionOut: {
            /** Id */
            id: string;
            /** Number */
            number: number;
            /** Excerpt */
            excerpt: string;
            /** Has Draft */
            has_draft: boolean;
        };
        /**
         * OverlayActOut
         * @description One pin or exclusion recorded on an entry (#157's entry read).
         *
         *     **Not ``ReadOverlayOut``**, which sits a few models above under a
         *     confusingly similar name and is a different concept: that one mirrors
         *     ``memoria.index.ReadOverlay`` and carries the
         *     ``entry_links``/``exclusions``/``citing_settlements`` a *paragraph* read
         *     is decorated with (#20). This one is an attributable author act stored
         *     on the entry file itself - part 04 §42's "never regenerated", which
         *     survives the index being deleted outright.
         *
         *     ``actor_name`` is served and ``actor_email`` is not. The address was
         *     withheld with the name when this model was written (#157) on the
         *     grounds that nothing in the client attributed a pin to a person; the
         *     entry view is that consumer, and part 06 §8.3 requires the overlay to be
         *     *attributable* on the surface that renders it - a gathered-set row
         *     marked "excluded" without saying by whom is an unexplained absence. The
         *     address stays withheld: ADR-0002 forbids assuming the browser and the
         *     repository share a machine, and an email crossing that boundary is a
         *     liability that no rendering needs.
         */
        OverlayActOut: {
            /** Anchor */
            anchor: string;
            /** Action */
            action: string;
            /** Actor Name */
            actor_name: string;
            /** At */
            at: string;
        };
        /**
         * Paragraph
         * @description One paragraph, carrying the stable anchor ``read(ref)`` accepts.
         *
         *     ``anchor`` comes from ``NormalizedRecord.anchor_id()`` - never
         *     re-derived as a string (#64's "where the fields come from").
         */
        Paragraph: {
            /** Anchor */
            anchor: string;
            /** Text */
            text: string;
        };
        /** QuestionOut */
        QuestionOut: {
            /** Text */
            text: string;
            /** Citation */
            citation: string;
        };
        /**
         * RawSourceResponse
         * @description The un-normalized file at ``original_file``, served as text.
         *
         *     ``original_locator`` is printed and never parsed - a pointer a person
         *     follows, not an offset (docs/normalized-record-schema.md).
         */
        RawSourceResponse: {
            /** Text */
            text: string;
            /** Original Locator */
            original_locator: string;
        };
        /**
         * ReadOverlayOut
         * @description The curated overlay a decorated paragraph read carries (#20):
         *     mirrors ``memoria.index.ReadOverlay`` field for field. ``citing_settlements``
         *     is always empty in this build - settlements have no durable storage yet
         *     (#20's own docstring) - and stays on the shape rather than being dropped,
         *     the same forward-compatibility call ``ReadOverlay`` itself makes.
         */
        ReadOverlayOut: {
            /** Entry Links */
            entry_links: string[];
            /** Exclusions */
            exclusions: string[];
            /** Citing Settlements */
            citing_settlements: string[];
        };
        /**
         * RevealSourceResponse
         * @description Confirms "Reveal in editor" (#65) launched.
         *
         *     Carries no other state - the editor or file manager runs on the host,
         *     outside this response.
         */
        RevealSourceResponse: {
            /** Opened */
            opened: boolean;
        };
        /**
         * ReviewOut
         * @description The Review surface: the results of an audit the author ran on one
         *     section, and nothing else (part 19 §19.11's amendment of §19.3).
         *
         *     ``findings`` is ordered by confidence. ``verdicts_current`` and
         *     ``verdicts_not_current`` count the section's (paragraph, entry) audit
         *     verdicts on each side of the staleness map: zero current is a section
         *     no audit has been run over, which the surface tells apart from an audit
         *     that found nothing. ``token`` is the draft's staleness token for
         *     ``PUT .../paragraphs/{index}`` to present back; ``None`` when the
         *     section has no draft.
         */
        ReviewOut: {
            /** Section Id */
            section_id: string;
            /** Chapter Number */
            chapter_number: number;
            /** Section Number */
            section_number: number;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Verdicts Current */
            verdicts_current: number;
            /** Verdicts Not Current */
            verdicts_not_current: number;
            /** Token */
            token?: string | null;
        };
        /**
         * RewriteResponse
         * @description What an accepted rewrite wrote, and a fresh token for the draft the
         *     write has just changed.
         */
        RewriteResponse: {
            /** Paragraph Index */
            paragraph_index: number;
            /** Text */
            text: string;
            /** Token */
            token: string;
        };
        /**
         * RewriteUpdate
         * @description The author applying a proposed rewrite to one paragraph - the
         *     interface act part 10 §19.3 names as authorization (``Apply``). ``token``
         *     is what ``ReviewOut`` served, presented back unread (ADR-0003).
         */
        RewriteUpdate: {
            /** Token */
            token: string;
            /** Text */
            text: string;
        };
        /**
         * ScopeEntryOut
         * @description One entry the brief's declared scope resolved to, and which of its
         *     match terms (or its own name) the brief text contains - the "how" half
         *     of ``memoria.scope.ScopeResolution``'s report.
         */
        ScopeEntryOut: {
            /** Entry Id */
            entry_id: string;
            /** Matched By */
            matched_by: string[];
        };
        /**
         * SearchResponse
         * @description A page of hits.
         *
         *     ``is_built`` is whether ``memoria rebuild`` has produced an index
         *     (``memoria.index.is_built``) - the same field as on
         *     ``SourceListResponse`` and ``SubjectListResponse``, reporting the third
         *     build step (#157). No results with ``is_built`` false means the corpus
         *     was never indexed, which is a different fact from nothing matching, and
         *     the two are the same empty list without it.
         */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchResultOut"][];
            /** Is Built */
            is_built: boolean;
        };
        /**
         * SearchResultOut
         * @description One search hit: the ``SRC-`` ID, the paragraph anchor, and a snippet.
         *
         *     ``memoria.index.SearchResult`` carries no paragraph text and this route
         *     serves none either, for the same reason ``search_text`` (#12) does not -
         *     see ``docs/tool-surface.md``'s "search_text(query, filters)" section,
         *     "What it returns", which is where that constraint is recorded.
         *
         *     ``snippet`` is not that text. It is the match locator #95 settled on: a
         *     truncated fragment of the index's copy, matched terms wrapped in
         *     ``index.SNIPPET_MATCH_START``/``_END``, for drawing a hit row (part 19
         *     §19.8). A client splits on those marks; it never renders the snippet as
         *     markup, and it never feeds it to ``read``. Evidence arrives when the
         *     reader clicks the hit and the slide-over reads ``anchor`` (§19.9).
         *
         *     Every field of ``index.SearchResult`` has a counterpart here, and
         *     ``test_web_app.py`` fails if one stops having one - the generated-types
         *     check cannot see a field the core has and this model dropped, because
         *     the schema stays self-consistent, just impoverished.
         */
        SearchResultOut: {
            /** Src Id */
            src_id: string;
            /** Anchor */
            anchor: string;
            /** Source Type */
            source_type: string;
            /** Snippet */
            snippet?: string | null;
        };
        /**
         * SectionParagraphOut
         * @description One draft paragraph, positionally numbered for this read only (part
         *     04 §4.1: no durable identity), with every not-current judgement the
         *     staleness map holds against it - what the surface tints, and why.
         */
        SectionParagraphOut: {
            /** Index */
            index: number;
            /** Text */
            text: string;
            /** Not Current */
            not_current: components["schemas"]["NotCurrentOut"][];
        };
        /**
         * SectionView
         * @description The Section surface (part 19 §19.5 as amended by §19.11): the brief
         *     (``PURPOSE`` - the one card that reads a file), the draft with its
         *     not-current tint, the entries in scope, and the decisions and open
         *     questions composed from the sessions that touched this section.
         *
         *     No ``checkpoint``, no ``next``, no ``impacts`` field, and never will be:
         *     those are withdrawn state (part 12 §39), not empty state.
         *     ``sessions`` names the session records the decisions and questions
         *     were composed from, so the composition is legible on the surface.
         */
        SectionView: {
            /** Id */
            id: string;
            /** Chapter Id */
            chapter_id: string;
            /** Chapter Number */
            chapter_number: number;
            /** Section Number */
            section_number: number;
            /** Brief */
            brief: string;
            /** Unconfirmed */
            unconfirmed: boolean;
            /** Has Draft */
            has_draft: boolean;
            /** Paragraphs */
            paragraphs: components["schemas"]["SectionParagraphOut"][];
            /** Scope */
            scope: components["schemas"]["ScopeEntryOut"][];
            /** Scope Empty */
            scope_empty: boolean;
            /** Sessions */
            sessions: string[];
            /** Decisions */
            decisions: components["schemas"]["DecisionOut"][];
            /** Questions */
            questions: components["schemas"]["QuestionOut"][];
        };
        /**
         * SourceDetail
         * @description A source read in full: frontmatter, verbatim paragraphs, apparatus.
         *
         *     ``apparatus`` is the linked editorial apparatus - footnotes, bracketed
         *     asides, interpolations, editors' introductions - as a **separate
         *     collection**, never interleaved into ``paragraphs`` (§6). It is always
         *     empty today: nothing produces editorial records or links them to the
         *     record they annotate yet (``memoria.index``'s note on ``source_type``),
         *     so this field exists to be filled once that linkage does, not to be
         *     faked in the meantime.
         */
        SourceDetail: {
            /** Id */
            id: string;
            /** Source Type */
            source_type: string;
            /** Recorded Date */
            recorded_date: string;
            /** Event Date */
            event_date: string;
            /** Date Confidence */
            date_confidence: string;
            /** Contemporaneous */
            contemporaneous: boolean;
            /** Original File */
            original_file: string;
            /** Original Locator */
            original_locator: string;
            /** Paragraphs */
            paragraphs: components["schemas"]["Paragraph"][];
            /**
             * Apparatus
             * @default []
             */
            apparatus: components["schemas"]["EditorialRecordOut"][];
        };
        /**
         * SourceListResponse
         * @description A page of ``list sources`` - paginated, per the acceptance criterion.
         *
         *     ``is_built`` is whether ``memoria normalize`` has produced anything here
         *     (``memoria.records.is_normalized``). It is what makes an empty ``items``
         *     readable: empty and ``false`` is an un-normalized checkout and the client
         *     should name the command to run; empty and ``true`` is a corpus that
         *     genuinely holds no sources. ADR-0004's "the empty corpus becomes a
         *     value" - this is the part of the value that says which state it is in
         *     (#157). The same field name appears on ``SubjectListResponse`` and
         *     ``SearchResponse``, each reporting its own build step.
         */
        SourceListResponse: {
            /** Items */
            items: components["schemas"]["SourceSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Is Built */
            is_built: boolean;
        };
        /**
         * SourceSummary
         * @description One record's frontmatter, and nothing else - the list view's row.
         *
         *     "List sources... Returns frontmatter only, never bodies" (#64): the
         *     paragraphs a record carries are not on this model, only on
         *     ``SourceDetail``.
         */
        SourceSummary: {
            /** Id */
            id: string;
            /** Source Type */
            source_type: string;
            /** Recorded Date */
            recorded_date: string;
            /** Event Date */
            event_date: string;
            /** Date Confidence */
            date_confidence: string;
            /** Contemporaneous */
            contemporaneous: boolean;
            /** Original File */
            original_file: string;
            /** Original Locator */
            original_locator: string;
        };
        /**
         * StatementOut
         * @description One paragraph of an entry body, with its badge if it has one -
         *     mirrors ``memoria.subjects.Statement`` field for field.
         *
         *     ``badge`` is ``None`` for author testimony, and that is not a missing
         *     value: **the absence of a badge is the attribution** (part 06 §9.5),
         *     which is why it is a nullable field on the shape rather than an omitted
         *     key. A response that dropped it would not be serving the entry.
         *     Non-null values are ``author``, ``source``, ``inferred`` and ``open``; a
         *     client renders whatever value is present rather than assuming that list
         *     is closed, the same posture ``SourceSummary.source_type`` takes.
         */
        StatementOut: {
            /** Badge */
            badge?: string | null;
            /** Text */
            text: string;
        };
        /**
         * SubjectListResponse
         * @description The `SUBJECTS` tree's top level.
         *
         *     ``is_built`` is whether ``memoria seed-subjects`` has run
         *     (``memoria.subjects.is_seeded``) - the same field, and the same
         *     distinction, as ``SourceListResponse.is_built``, reporting a different
         *     build step (#157). It reports the ``subjects/`` directory's existence
         *     rather than its contents, so a directory holding no subject prompts
         *     reads as built-and-empty; ``is_seeded`` records why.
         */
        SubjectListResponse: {
            /** Items */
            items: components["schemas"]["SubjectSummary"][];
            /** Is Built */
            is_built: boolean;
        };
        /**
         * SubjectSummary
         * @description One subject - the `SUBJECTS` tree's top level (#24).
         *
         *     ``entry_count`` is computed from the entries actually on disk, never
         *     hardcoded (#24's acceptance criteria) - the same discipline
         *     ``SourceListResponse.total`` keeps for sources.
         */
        SubjectSummary: {
            /** Id */
            id: string;
            /** Entry Count */
            entry_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sources_api_sources_get: {
        parameters: {
            query?: {
                source_type?: string | null;
                date_confidence?: string | null;
                contemporaneous?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_source_api_sources__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raw_source_api_sources__record_id__raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locality_api_locality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalityOut"];
                };
            };
        };
    };
    reveal_source_api_sources__record_id__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_read_get: {
        parameters: {
            query: {
                ref: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_api_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectListResponse"];
                };
            };
        };
    };
    list_entries_api_subjects__subject_id__entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_entry_api_subjects__subject_id__entries__entry_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
                entry_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_gathered_set_api_subjects__subject_id__entries__entry_slug__gathered_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
                entry_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheredSetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_appearances_api_subjects__subject_id__entries__entry_slug__appearances_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
                entry_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppearancesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_terms_api_subjects__subject_id__entries__entry_slug__match_terms_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
                entry_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchTermsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchTermsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                event_date?: string | null;
                recorded_date?: string | null;
                source_type?: string | null;
                contemporaneous?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_manuscript_api_manuscript_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManuscriptOutline"];
                };
            };
        };
    };
    read_section_api_sections__section_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_review_api_sections__section_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rewrite_paragraph_api_sections__section_id__paragraphs__paragraph_index__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
                paragraph_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewriteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
