"""The single write path: a content-hash staleness check, then a
path-scoped commit.

ADR-0003 settles the mechanism and ADR-0004 settles where it lives - a
module of its own, taking the same frozen ``Repository`` value the read
modules take, not a shared object, so the staleness token crosses between
core modules as an explicit value rather than as hidden state. This module
carries every write to a durable state class (part 04 §3): Manuscript,
Subjects, Claims, Working state and Change record. Evidence and Interaction
record are immutable once created, and Derived state - normalized records
(``memoria.records``), the search index (``memoria.index``), and the
gitignored ``changes/`` projection (ADR-0008) - is regenerated by
``memoria rebuild`` and carries no authority (§42), so none of it goes
through here.

**What this deliberately does not do**, so it is not later mistaken for an
omission: no locking, no queue, no reconciliation, no merge, no multi-file
atomicity, and no creation - a token is minted from a file that exists, so
a path with no file behind it never matches one, and a new durable file
is not this issue's to bring into being. A write applies to the file the
client read, whole, or it is rejected and says so. A residual TOCTOU window
between the staleness check and the write is knowingly accepted (ADR-0003)
- closing it needs a lock, and Obsidian will never take one.
"""

from __future__ import annotations

import hashlib
import os
import subprocess
import uuid
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from memoria.repository import Repository

# The durable state classes (part 04 §3) this module owns every write to,
# named by their repository-relative path prefixes. Evidence (`sources/`),
# Interaction record (`sessions/`) and Derived state (`sources/normalized/`,
# `.memoria/`, `changes/`) are deliberately absent - see the module
# docstring. Enumerated here, in one place: `serve` and `write` refuse a
# path outside them, and a test asserts nothing else in the codebase writes
# a file at all.
DURABLE_PATHS = (
    "book.md",
    "chapters/",
    "subjects/",
    "claims/",
    "decisions.md",
    "questions.md",
    "research/",
)


class WriteError(Exception):
    """Raised for a write that cannot be attempted at all - a path escaping
    the repository or naming something outside the durable classes, or the
    underlying git commit failing.

    Distinct from a stale token, which is not exceptional: it is the normal
    ``Rejected`` outcome the caller is expected to see and handle (decision
    5), not an error.
    """


@dataclass(frozen=True)
class Actor:
    """Who a commit is attributed to (decision 2). An author's edit through
    a surface commits as theirs; a Curator pass commits as the machine
    (§41)."""

    name: str
    email: str


@dataclass(frozen=True)
class Served:
    """A durable file, read for editing. ``token`` is what a later `write`
    call must present unchanged for the write to apply."""

    path: str
    text: str
    token: str


@dataclass(frozen=True)
class Written:
    """A write applied exactly, and was committed."""

    path: str


@dataclass(frozen=True)
class Rejected:
    """A write was refused. Carries the outcome and the file path, and
    nothing else (decision 5) - not the current contents; #64 already
    builds the read, and the client re-reads through `serve` for those and
    a fresh token."""

    outcome: str
    path: str


WriteResult = Written | Rejected


def serve(repository: Repository, relative_path: str) -> Served:
    """Read a durable file for editing, and mint its staleness token.

    The same hash function mints the token here and checks it in `write`,
    so the two directions cannot drift - the discipline
    ``memoria.records`` keeps between its serializer and its parser.
    """
    path = _confined(repository, PurePosixPath(relative_path))
    data = path.read_bytes()
    return Served(path=relative_path, text=data.decode("utf-8"), token=_token(data))


def write(
    repository: Repository,
    relative_path: str,
    token: str,
    content: str,
    actor: Actor,
) -> WriteResult:
    """Apply one write to one durable file, gated by its staleness token.

    Decision 1: the token is a content hash, not a git revision - compared
    against the file's current bytes on disk, opaque to the caller. A
    mismatch is `Rejected`, naming the file; nothing is merged, reconciled
    or partially applied.

    Decision 3: replaced whole, via a temp file and `rename()`, so a crash
    mid-write leaves the original intact and no reader ever sees a partial
    file.

    Decision 2: an accepted write commits, path-scoped to `relative_path`
    and attributed to `actor` - never `git add -A`, so an unrelated dirty
    file is neither committed nor cleaned.
    """
    path = _confined(repository, PurePosixPath(relative_path))
    if _current_token(path) != token:
        return Rejected(outcome="stale", path=relative_path)
    _replace_atomically(path, content)
    _commit(repository, relative_path, actor)
    return Written(path=relative_path)


def _token(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _current_token(path: Path) -> str | None:
    """The file's token, or ``None`` if it does not exist - which never
    equals a real token, so a write against a file that has vanished is
    rejected like any other mismatch rather than crashing here."""
    if not path.is_file():
        return None
    return _token(path.read_bytes())


def _confined(repository: Repository, path: PurePosixPath) -> Path:
    """Resolve a repository-relative path, refusing anything outside the
    root - the same second-stage check ``memoria.records`` makes on the
    read side, against the resolved path rather than the string a caller
    wrote."""
    resolved = (repository.root / path).resolve()
    root = repository.root.resolve()
    if resolved != root and root not in resolved.parents:
        raise WriteError(f"path escapes the repository: {path}")
    if not str(path).startswith(DURABLE_PATHS):
        raise WriteError(f"not a durable state class path: {path}")
    return resolved


def _replace_atomically(path: Path, content: str) -> None:
    tmp = path.with_name(f"{path.name}.tmp-{uuid.uuid4().hex}")
    tmp.write_text(content, encoding="utf-8")
    try:
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise


def _commit(repository: Repository, relative_path: str, actor: Actor) -> None:
    # Env, not `--author`, so the commit needs no `user.name`/`user.email`
    # configured for this repository - the identity is `actor`, in full,
    # author and committer alike.
    env = {
        **os.environ,
        "GIT_AUTHOR_NAME": actor.name,
        "GIT_AUTHOR_EMAIL": actor.email,
        "GIT_COMMITTER_NAME": actor.name,
        "GIT_COMMITTER_EMAIL": actor.email,
    }
    # `add` before `commit`, explicitly, so a file git does not track yet -
    # on disk but never committed - is picked up too; `git commit
    # <pathspec>` alone only re-stages a path git already tracks. Every call
    # is scoped to `relative_path` and nothing else, so another dirty file
    # already staged is neither committed nor cleaned.
    _git(repository, ["add", "--", relative_path], env=env)
    # Saving the bytes that were read is an ordinary save, not an error:
    # the file was replaced with itself and there is nothing to record, so
    # no commit - `git commit` would exit 1 on `nothing to commit`.
    if _git(repository, ["diff", "--cached", "--quiet", "--", relative_path],
            env=env, ok=(0, 1)) == 0:
        return
    _git(
        repository,
        ["commit", "-m", f"write: {relative_path}", "--", relative_path],
        env=env,
    )


def _git(
    repository: Repository, args: list[str], *, env: dict, ok: tuple[int, ...] = (0,)
) -> int:
    """Run git, returning its exit code if it is one of `ok`. Any other is a
    `WriteError` quoting both streams - git reports some failures on
    stdout, not stderr."""
    result = subprocess.run(
        ["git", *args],
        cwd=repository.root,
        env=env,
        capture_output=True,
        text=True,
    )
    if result.returncode not in ok:
        reason = " ".join(part.strip() for part in (result.stdout, result.stderr) if part.strip())
        raise WriteError(f"git {' '.join(args)} failed: {reason}")
    return result.returncode
