#!/usr/bin/env python3
"""Regenerate `docs/answer-key-spot-check.md` from the committed answer key.

The spot check is six resolved rows drawn with a fixed seed, each showing the
scanned Manuscript page beside the held paragraphs the key says it covers, so
a human can answer one question per row: does the cited page hold that text?
It is not a formality - the one-page leaf-numbering offset that had put 243 of
360 rows one page late was caught here and nowhere else
(`docs/answer-key-protocol.md`).

**Why this is a script and not part of `memoria normalize`.** Everything
normalize writes is derived state that can be thrown away and rebuilt. This
document is the opposite: it is regenerated by machine but *completed by hand*,
and the verdicts a person writes into it are the only part that matters. So it
is regenerated deliberately, when the key changes, and never as a side effect
of a rebuild - and this script refuses to overwrite verdicts that have been
filled in (see `--force`).

The sample changes whenever the set of resolved rows changes, because the seed
draws from that set. That is the point: a sample fixed against an older key
would be checking rows the key no longer contains.

Usage, from anywhere in the repo:

    MEMORIA_EVIDENCE_ROOT=../thoreau-evidence .venv/bin/python scripts/spot-check.py
"""

from __future__ import annotations

import argparse
import random
import re
import sys
import textwrap
from pathlib import Path

import yaml

from memoria.answer_key import ANSWER_KEY_RELATIVE_PATH
from memoria.cli import evidence_root, repo_root
from memoria.editions import REFERENCE_EDITIONS, read_reference_volume

SPOT_CHECK_RELATIVE_PATH = "docs/answer-key-spot-check.md"

# The sampling the document describes in its own opening paragraph. One
# generator shared across both works, works in this order: changing any of it
# changes which six rows are drawn, so it is stated here rather than inlined.
SEED = 9
PER_WORK = 3
WORKS = ("Week", "Walden")

# The scanned page's first and last few words, quoted above the span so the
# check is "find these two, in this order" rather than "read both texts".
CONTEXT_WORDS = 12

# Matches the prose already in the file; markdown reflows anyway, but a stable
# width keeps the diff between two regenerations readable.
WRAP = 76

# `[^\S\n]` and not `\s`: `\s` crosses the newline and matches the `---` rule
# that follows an empty verdict, so every blank check reads as filled in.
_FILLED_VERDICT_RE = re.compile(r"^\*\*Verdict:\*\*[^\S\n]*\S", re.MULTILINE)


def draw(resolved: list[dict]) -> list[str]:
    """The six link IDs, drawn reproducibly from the resolved rows."""
    rng = random.Random(SEED)
    drawn: list[str] = []
    for work in WORKS:
        pool = sorted(r["link_id"] for r in resolved if r["target_work"] == work)
        drawn += rng.sample(pool, PER_WORK)
    return drawn


def render_row(number: int, row: dict, page_text: str) -> list[str]:
    words = " ".join(page_text.split()).split()
    page = row["manuscript_pages"][0]
    anchors = row["target_anchors"]
    return [
        "---",
        "",
        f"## {number}. `{row['link_id']}`",
        "",
        f"- Footnote: `{row['citation']}`",
        f"- Key says: **{row['target_locator']}**",
        (
            f"- Anchors: `{anchors[0]}` … `{anchors[-1]}`"
            if len(anchors) > 1
            else f"- Anchor: `{anchors[0]}`"
        ),
        f"- Edition cross-check: Riverside p. {row['riverside_pages'][0]}, "
        f"residual {row['residual_pages']:+.2f} pages",
        "",
        "**Look for these, in the span below:**",
        "",
        f"- opens: `{' '.join(words[:CONTEXT_WORDS])}`",
        f"- closes: `{' '.join(words[-CONTEXT_WORDS:])}`",
        "",
        "<details>",
        f"<summary>Manuscript Edition page {page}, as scanned "
        f"({len(words)} words)</summary>",
        "",
        "```",
        textwrap.fill(" ".join(words), width=WRAP),
        "```",
        "</details>",
        "",
        f"### Held text, {row['target_locator']}",
        "",
        "```",
        textwrap.fill(" ".join(row["target_text"].split()), width=WRAP),
        "```",
        "",
        "**Verdict:** ",
        "",
    ]


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="spot-check.py")
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite even if verdicts have already been filled in",
    )
    args = parser.parse_args(argv)

    root = repo_root()
    output_path = root / SPOT_CHECK_RELATIVE_PATH
    existing = output_path.read_text(encoding="utf-8")

    if _FILLED_VERDICT_RE.search(existing) and not args.force:
        print(
            f"spot-check: {SPOT_CHECK_RELATIVE_PATH} has verdicts filled in, "
            "and regenerating would discard them. Pass --force if the key has "
            "changed and the check genuinely has to be walked again.",
            file=sys.stderr,
        )
        return 1

    key = yaml.safe_load(
        (root / ANSWER_KEY_RELATIVE_PATH).read_text(encoding="utf-8")
    )
    resolved = [link for link in key["links"] if link["status"] == "resolved"]
    by_id = {link["link_id"]: link for link in resolved}

    # Only the Manuscript scans: the Riverside page is the corroborating
    # evidence the key already applied, and showing it too would turn a
    # two-text comparison into a three-text one for no gain.
    volumes = {
        edition["work"]: read_reference_volume(
            evidence_root(), edition["identifier"]
        )
        for edition in REFERENCE_EDITIONS
        if edition["series"] == "manuscript"
    }

    # Everything above the first rule is prose about what is being checked and
    # is kept, not templated - so an edit to that explanation survives a
    # regeneration.
    parts = [existing.split("\n---\n")[0].rstrip("\n"), ""]
    drawn = draw(resolved)
    for number, link_id in enumerate(drawn, start=1):
        row = by_id[link_id]
        page = row["manuscript_pages"][0]
        parts += render_row(number, row, volumes[row["target_work"]].pages[page])
    parts.append("---")

    output_path.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"spot-check: wrote {SPOT_CHECK_RELATIVE_PATH}: {', '.join(drawn)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
